- distributed_05.rst
- migration.rst
- setup_by_centos7.rst
- setup_by_centos8.rst
- setup_by_localcloud.rst
- setup_by_ubuntu18.rst
- step_by_step.rst
> [Fix]修复安装失败

- faq.rst
- setup_by_fast.rst
> [Update]更新文档

- docs/dev/build.md
- mkdocs.yml
> fix: 修正编译错误

- docs/admin-guide/proxy.md
> perf: 添加二级代理说明

- docs/01_primary_directory/architecture.md
- docs/02_jms_install/source_install/core_install.md
- docs/02_jms_install/source_install/koko_install.md
- docs/02_jms_install/source_install/lina_install.md
- docs/02_jms_install/source_install/lion_install.md
- docs/02_jms_install/source_install/luna_install.md
- docs/02_jms_install/source_install/magnus_install.md
- docs/02_jms_install/source_install/merge_jumpserver.md
- docs/02_jms_install/source_install/nginx_install.md
- docs/02_jms_install/source_install/requirements.md
- mkdocs.yml
> perf: 目录结构调整

- docs/index.md
- mkdocs.yml
> fix: 修改首页 index 文件路径

- docs/jms_install/linux_lb/redis_install.md
- docs/jms_install/linux_stand-alone/on_line_install.md
- docs/quick_start.md
> fix: 修改快速安装命令

- docs/css/extra.css
- theme/css/f2c-header.css
- theme/f2c-header.html
- theme/js/bootstrap.min.js
- theme/main.html
> perf: 更新首页上方学习中心内容

- theme/f2c-header.html
> perf: 优化学习班标语话术

- docs/faq/faq.md
- theme/f2c-header.html
> perf: 优化学习班标题，优化FAQ链接

- docs/index.md
> perf: 优化index首页内容链接

- mkdocs.yml
> perf: 优化首页Bilibili 官方站地址

- docs/installation/source_install/merge_jumpserver.md
- fix: jumpserver/jumpserver#10022
> fix: 修复源码部署缺失 ws

- theme/f2c-header.html
> perf: 更新学习班链接

- theme/f2c-header.html
> perf: 增加线下体验营链接、优化样式

- theme/css/f2c-header.css
- theme/f2c-header.html
> fix: 优化学习班链接样式

- theme/f2c-header.html
> fix: 修复首页产品下拉框链接跳转失败

- docs/dev/rest_api.md
perf: 增加API文档中AKSK和Token认证的Java示例
> perf: 增加API文档中AKSK和Token认证的Java示例

- docs/change_log.md
> feat: Update v3.5.0

- mkdocs.yml
> fix: 修正版本号

- mkdocs.yml
> fix: 优化目录排序

- mkdocs.yml
> fix: v3.6.2 版本号修改

- theme/f2c-header.html
> perf: 更新学习班11期链接

- theme/f2c-header.html
> yzj_dev_v3

- docs/css/extra.css
- theme/f2c-header.html
- theme/main.html
> perf: 删除学习班链接

- theme/main.html
> feat: 小助手测试

- theme/main.html
> feat: 对接小助手功能

- theme/css/f2c-header.css
- theme/f2c-header.html
> style: 修改导航栏样式

- docs/installation/jmsctl_sh.md
> perf: 更新jmsctl

- docs/faq/v2_timeline.md
> perf: 生命周期内容更新

- docs/index.md
> Coxi dev v2

- docs/faq/faq.md
- docs/manual/admin/system_settings/notification_settings.md
> Notification model@v4
